import type {
  Garment,
  Creator,
  Pattern,
  Project,
  SewingStep,
  PatternPiece,
  FabricOption,
} from './types'

export const garments: Garment[] = [
  {
    id: 'classic-tshirt',
    name: 'Classic T-Shirt',
    category: 'Tops',
    difficulty: 'Beginner',
    estimatedTime: '3–4 hours',
    price: 9,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    description: 'The perfect first project. Learn the fundamentals of sewing with this timeless wardrobe staple.',
  },
  {
    id: 'aline-skirt',
    name: 'A-Line Skirt',
    category: 'Bottoms',
    difficulty: 'Beginner',
    estimatedTime: '2–3 hours',
    price: 8,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    description: 'A flattering and simple skirt shape, perfect for beginners building their first wardrobe.',
  },
  {
    id: 'straight-trousers',
    name: 'Straight Trousers',
    category: 'Bottoms',
    difficulty: 'Intermediate',
    estimatedTime: '5–6 hours',
    price: 12,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    description: 'Classic straight-leg trousers that work for every occasion. A great next step after your first projects.',
  },
  {
    id: 'oversized-hoodie',
    name: 'Oversized Hoodie',
    category: 'Tops',
    difficulty: 'Intermediate',
    estimatedTime: '4–5 hours',
    price: 11,
    isCreator: false,
    fits: ['Oversized', 'Relaxed'],
    description: 'Cosy and versatile, this hoodie is a wardrobe essential. Learn drawstrings, cuffs, and kangaroo pockets.',
  },
  {
    id: 'slip-dress',
    name: 'Slip Dress',
    category: 'Dresses',
    difficulty: 'Intermediate',
    estimatedTime: '3–4 hours',
    price: 10,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    description: 'Elegant and effortless. This bias-cut slip dress teaches you to work with silky fabrics.',
  },
  {
    id: 'tailored-blazer',
    name: 'Tailored Blazer',
    category: 'Outerwear',
    difficulty: 'Advanced',
    estimatedTime: '8–10 hours',
    price: 15,
    isCreator: false,
    fits: ['Regular', 'Fitted'],
    description: 'The pinnacle of garment construction. Master lapels, lining, and structured tailoring.',
  },
]

export const creators: Creator[] = [
  {
    id: 'studio-by-mia',
    handle: '@studio.by.mia',
    name: 'Mia Johansson',
    bio: 'Minimal, wearable patterns for every body. Based in Stockholm.',
    followerCount: '24.3k',
    isCertified: true,
    patternCount: 18,
    avatarColor: '#C4A882',
  },
  {
    id: 'sewing-with-frida',
    handle: '@sewingwithfrida',
    name: 'Frida Larsen',
    bio: 'Sustainable fashion designer & educator. Making sewing joyful.',
    followerCount: '18.7k',
    isCertified: true,
    patternCount: 12,
    avatarColor: '#A8BFA8',
  },
  {
    id: 'fabric-diaries',
    handle: '@thefabricdiaries',
    name: 'The Fabric Diaries',
    bio: 'Slow fashion patterns inspired by vintage silhouettes.',
    followerCount: '31.2k',
    isCertified: false,
    patternCount: 24,
    avatarColor: '#BFA8C4',
  },
]

export const creatorPatterns: Pattern[] = [
  {
    id: 'mia-linen-set',
    garmentId: 'mia-linen-top',
    creatorId: 'studio-by-mia',
    name: 'Linen Co-ord Set',
    price: 14,
    difficulty: 'Intermediate',
    fit: 'Relaxed',
    timesMade: 1247,
    category: 'Tops',
  },
  {
    id: 'mia-wrap-dress',
    garmentId: 'mia-wrap-dress',
    creatorId: 'studio-by-mia',
    name: 'Studio Wrap Dress',
    price: 12,
    difficulty: 'Beginner',
    fit: 'Regular',
    timesMade: 892,
    category: 'Dresses',
  },
  {
    id: 'frida-cargo',
    garmentId: 'frida-cargo-pants',
    creatorId: 'sewing-with-frida',
    name: 'Utility Cargo Trousers',
    price: 13,
    difficulty: 'Intermediate',
    fit: 'Relaxed',
    timesMade: 634,
    category: 'Bottoms',
  },
  {
    id: 'frida-blouse',
    garmentId: 'frida-peasant-blouse',
    creatorId: 'sewing-with-frida',
    name: 'Peasant Blouse',
    price: 9,
    difficulty: 'Beginner',
    fit: 'Oversized',
    timesMade: 1831,
    category: 'Tops',
  },
  {
    id: 'tfd-coat',
    garmentId: 'tfd-cocoon-coat',
    creatorId: 'fabric-diaries',
    name: 'Cocoon Coat',
    price: 15,
    difficulty: 'Advanced',
    fit: 'Relaxed',
    timesMade: 412,
    category: 'Outerwear',
  },
  {
    id: 'tfd-culottes',
    garmentId: 'tfd-wide-culottes',
    creatorId: 'fabric-diaries',
    name: 'Wide-Leg Culottes',
    price: 10,
    difficulty: 'Beginner',
    fit: 'Relaxed',
    timesMade: 2104,
    category: 'Bottoms',
  },
]

export const activeProject: Project = {
  id: 'proj-1',
  garmentId: 'classic-tshirt',
  garmentName: 'Classic T-Shirt',
  difficulty: 'Beginner',
  status: 'active',
  progressPercent: 42,
  startedAt: '2026-07-15',
}

export const completedProjects: Project[] = [
  {
    id: 'proj-completed-1',
    garmentId: 'aline-skirt',
    garmentName: 'A-Line Skirt',
    difficulty: 'Beginner',
    status: 'completed',
    progressPercent: 100,
    startedAt: '2026-06-20',
    completedAt: '2026-06-22',
    userPhotoColor: '#C4A882',
  },
]

export const tshirtSteps: SewingStep[] = [
  {
    id: 1,
    title: 'Cut the front panel',
    description: 'Place pattern piece A face-down on your folded fabric. Pin carefully along the edges. Cut around the pattern leaving a 1.5 cm seam allowance on all sides.',
    measurement: '1.5 cm seam allowance',
    highlight: 'front',
    camera: { position: [0, 0.1, 3.2], target: [0, -0.1, 0] },
  },
  {
    id: 2,
    title: 'Cut the back panel',
    description: 'Repeat with pattern piece B for the back. Make sure to transfer all notch markings — they\'ll guide you when joining pieces later.',
    measurement: '1.5 cm seam allowance',
    highlight: 'back',
    camera: { position: [0, 0.1, -3.2], target: [0, -0.1, 0] },
  },
  {
    id: 3,
    title: 'Pin the shoulder seams',
    description: 'Place front and back panels right sides together. Match the shoulder notches carefully and pin every 5 cm along the shoulder line.',
    measurement: '5 cm between pins',
    highlight: 'shoulder',
    camera: { position: [0, 1.8, 2.2], target: [0, 0.5, 0] },
  },
  {
    id: 4,
    title: 'Sew the shoulder seams',
    description: 'Sew along each shoulder seam with a straight stitch. Start and end with a few backstitches to lock the thread. Press the seam open with your iron.',
    measurement: '1.5 cm from edge',
    stitchType: 'Straight stitch',
    highlight: 'shoulder',
    camera: { position: [0, 1.8, 2.2], target: [0, 0.5, 0] },
  },
  {
    id: 5,
    title: 'Pin the side seams',
    description: 'Open your garment flat and fold right sides together again. Match the side notches and pin from armhole down to the hem.',
    measurement: '1.5 cm seam allowance',
    highlight: 'side',
    camera: { position: [2.8, 0, 0.5], target: [0, 0, 0] },
  },
  {
    id: 6,
    title: 'Sew the side seams',
    description: 'Sew both side seams with a straight stitch. If your fabric stretches, use a narrow zigzag stitch instead. Press seams towards the back.',
    measurement: '1.5 cm from edge',
    stitchType: 'Straight stitch',
    highlight: 'side',
    camera: { position: [2.8, 0, 0.5], target: [0, 0, 0] },
  },
  {
    id: 7,
    title: 'Attach the sleeves',
    description: 'With the body inside out, slide a sleeve in through the armhole, right sides together. Match the sleeve cap notch to the shoulder seam. Pin and sew around the armhole.',
    measurement: '1.5 cm seam allowance',
    stitchType: 'Straight stitch',
    highlight: 'sleeve',
    camera: { position: [2.2, 0.6, 1.8], target: [0.3, 0.3, 0] },
  },
  {
    id: 8,
    title: 'Hem the neckline',
    description: 'Fold the neckline edge under by 0.5 cm then again by 1 cm. Pin in place. Sew close to the fold with a straight stitch, stretching slightly as you go if the fabric is jersey.',
    measurement: '0.5 cm + 1 cm fold',
    stitchType: 'Stretch stitch',
    highlight: 'collar',
    camera: { position: [0, 2.2, 1.8], target: [0, 0.6, 0] },
  },
  {
    id: 9,
    title: 'Hem the sleeve ends',
    description: 'Fold each sleeve end under by 0.5 cm then 1.5 cm. Pin and sew in place. The key is to keep even tension all the way around.',
    measurement: '0.5 cm + 1.5 cm fold',
    stitchType: 'Straight stitch',
    highlight: 'sleeve',
    camera: { position: [2.6, -0.5, 1.0], target: [0.6, -0.2, 0] },
  },
  {
    id: 10,
    title: 'Sew the bottom hem',
    description: 'Turn up the bottom edge by 0.5 cm then 2.5 cm. Press well with your iron — this makes sewing straight so much easier. Sew close to the upper fold.',
    measurement: '0.5 cm + 2.5 cm fold',
    stitchType: 'Straight stitch',
    highlight: 'hem',
    camera: { position: [0, -1.8, 2.6], target: [0, -0.6, 0] },
  },
  {
    id: 11,
    title: 'Press all seams',
    description: 'Give every seam a final press with a hot iron. This step makes a huge difference to the finished look — professional garments are pressed at every stage.',
    highlight: 'all',
    camera: { position: [0, 0.5, 4.0], target: [0, 0, 0] },
  },
  {
    id: 12,
    title: 'Your t-shirt is finished!',
    description: 'You made this from scratch. Try it on, admire your work, and celebrate — you\'re a maker now.',
    highlight: 'all',
    camera: { position: [0, 0.5, 4.0], target: [0, 0, 0] },
  },
]

export const tshirtPatternPieces: PatternPiece[] = [
  { id: 'A', label: 'A', name: 'Front Panel', width: 52, height: 68, quantity: 1 },
  { id: 'B', label: 'B', name: 'Back Panel', width: 52, height: 66, quantity: 1 },
  { id: 'C', label: 'C', name: 'Left Sleeve', width: 38, height: 24, quantity: 1 },
  { id: 'D', label: 'D', name: 'Right Sleeve', width: 38, height: 24, quantity: 1 },
]

export const tshirtFabrics: FabricOption[] = [
  {
    name: 'Jersey Cotton',
    description: 'Soft, stretchy, and forgiving for beginners. Washes beautifully.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
  },
  {
    name: 'French Terry',
    description: 'Slightly thicker than jersey, with a looped back. Cozy and durable.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
    isEco: true,
  },
  {
    name: 'Viscose Jersey',
    description: 'Drapey and silky feel. A step up in difficulty — slippery to cut.',
    difficulty: 'Medium',
    quantityMeters: 2.0,
  },
  {
    name: 'Organic Cotton Jersey',
    description: 'Better for the environment. Slightly stiffer than regular cotton jersey.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
    isEco: true,
  },
]

export const getGarmentById = (id: string) =>
  garments.find((g) => g.id === id) ?? garments[0]

export const getCreatorById = (id: string) =>
  creators.find((c) => c.id === id) ?? creators[0]

export const getPatternsByCreator = (creatorId: string) =>
  creatorPatterns.filter((p) => p.creatorId === creatorId)
