import type {
  Garment,
  Creator,
  Pattern,
  Project,
  SewingStep,
  PatternPiece,
  FabricOption,
  GarmentGuide,
  UserMeasurements,
  StandardSize,
} from './types'

export const garments: Garment[] = [
  {
    id: 'classic-tshirt',
    name: 'Classic T-Shirt',
    category: 'Tops',
    difficulty: 'Beginner',
    estimatedTime: '3–4 hours',
    price: 9,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    description: 'The perfect first project. Learn the fundamentals of sewing with this timeless wardrobe staple.',
  },
  {
    id: 'aline-skirt',
    name: 'A-Line Skirt',
    category: 'Bottoms',
    difficulty: 'Beginner',
    estimatedTime: '2–3 hours',
    price: 8,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'A flattering and simple skirt shape, perfect for beginners building their first wardrobe.',
  },
  {
    id: 'straight-trousers',
    name: 'Straight Trousers',
    category: 'Bottoms',
    difficulty: 'Intermediate',
    estimatedTime: '5–6 hours',
    price: 12,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'Classic straight-leg trousers that work for every occasion. A great next step after your first projects.',
  },
  {
    id: 'oversized-hoodie',
    name: 'Oversized Hoodie',
    category: 'Tops',
    difficulty: 'Intermediate',
    estimatedTime: '4–5 hours',
    price: 11,
    isCreator: false,
    fits: ['Oversized', 'Relaxed'],
    sizes: ['S', 'M', 'L', 'XL'],
    description: 'Cosy and versatile, this hoodie is a wardrobe essential. Learn drawstrings, cuffs, and kangaroo pockets.',
  },
  {
    id: 'slip-dress',
    name: 'Slip Dress',
    category: 'Dresses',
    difficulty: 'Intermediate',
    estimatedTime: '3–4 hours',
    price: 10,
    isCreator: false,
    fits: ['Relaxed', 'Regular', 'Fitted'],
    sizes: ['XS', 'S', 'M', 'L'],
    description: 'Elegant and effortless. This bias-cut slip dress teaches you to work with silky fabrics.',
  },
  {
    id: 'tailored-blazer',
    name: 'Tailored Blazer',
    category: 'Outerwear',
    difficulty: 'Advanced',
    estimatedTime: '8–10 hours',
    price: 15,
    isCreator: false,
    fits: ['Regular', 'Fitted'],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    description: 'The pinnacle of garment construction. Master lapels, lining, and structured tailoring.',
  },
]

export const creators: Creator[] = [
  {
    id: 'studio-by-mia',
    handle: '@studio.by.mia',
    name: 'Mia Johansson',
    bio: 'Minimal, wearable patterns for every body. Based in Stockholm.',
    followerCount: '24.3k',
    isCertified: true,
    patternCount: 18,
    avatarColor: '#C4A882',
  },
  {
    id: 'sewing-with-frida',
    handle: '@sewingwithfrida',
    name: 'Frida Larsen',
    bio: 'Sustainable fashion designer & educator. Making sewing joyful.',
    followerCount: '18.7k',
    isCertified: true,
    patternCount: 12,
    avatarColor: '#A8BFA8',
  },
  {
    id: 'fabric-diaries',
    handle: '@thefabricdiaries',
    name: 'The Fabric Diaries',
    bio: 'Slow fashion patterns inspired by vintage silhouettes.',
    followerCount: '31.2k',
    isCertified: false,
    patternCount: 24,
    avatarColor: '#BFA8C4',
  },
]

export const creatorPatterns: Pattern[] = [
  {
    id: 'mia-linen-set',
    garmentId: 'mia-linen-top',
    creatorId: 'studio-by-mia',
    name: 'Linen Co-ord Set',
    price: 14,
    difficulty: 'Intermediate',
    fit: 'Relaxed',
    timesMade: 1247,
    category: 'Tops',
  },
  {
    id: 'mia-wrap-dress',
    garmentId: 'mia-wrap-dress',
    creatorId: 'studio-by-mia',
    name: 'Studio Wrap Dress',
    price: 12,
    difficulty: 'Beginner',
    fit: 'Regular',
    timesMade: 892,
    category: 'Dresses',
  },
  {
    id: 'frida-cargo',
    garmentId: 'frida-cargo-pants',
    creatorId: 'sewing-with-frida',
    name: 'Utility Cargo Trousers',
    price: 13,
    difficulty: 'Intermediate',
    fit: 'Relaxed',
    timesMade: 634,
    category: 'Bottoms',
  },
  {
    id: 'frida-blouse',
    garmentId: 'frida-peasant-blouse',
    creatorId: 'sewing-with-frida',
    name: 'Peasant Blouse',
    price: 9,
    difficulty: 'Beginner',
    fit: 'Oversized',
    timesMade: 1831,
    category: 'Tops',
  },
  {
    id: 'tfd-coat',
    garmentId: 'tfd-cocoon-coat',
    creatorId: 'fabric-diaries',
    name: 'Cocoon Coat',
    price: 15,
    difficulty: 'Advanced',
    fit: 'Relaxed',
    timesMade: 412,
    category: 'Outerwear',
  },
  {
    id: 'tfd-culottes',
    garmentId: 'tfd-wide-culottes',
    creatorId: 'fabric-diaries',
    name: 'Wide-Leg Culottes',
    price: 10,
    difficulty: 'Beginner',
    fit: 'Relaxed',
    timesMade: 2104,
    category: 'Bottoms',
  },
]

export const activeProject: Project = {
  id: 'proj-1',
  garmentId: 'classic-tshirt',
  garmentName: 'Classic T-Shirt',
  difficulty: 'Beginner',
  status: 'active',
  progressPercent: 42,
  startedAt: '2026-07-15',
}

export const completedProjects: Project[] = [
  {
    id: 'proj-completed-1',
    garmentId: 'aline-skirt',
    garmentName: 'A-Line Skirt',
    difficulty: 'Beginner',
    status: 'completed',
    progressPercent: 100,
    startedAt: '2026-06-20',
    completedAt: '2026-06-22',
    userPhotoColor: '#C4A882',
  },
]

export const tshirtSteps: SewingStep[] = [
  {
    id: 1,
    title: 'Cut the front panel',
    description: 'Place pattern piece A face-down on your folded fabric. Pin carefully along the edges. Cut around the pattern leaving a 1.5 cm seam allowance on all sides.',
    measurement: '1.5 cm seam allowance',
    highlight: 'front',
    camera: { position: [0, 0.1, 3.2], target: [0, -0.1, 0] },
  },
  {
    id: 2,
    title: 'Cut the back panel',
    description: 'Repeat with pattern piece B for the back. Make sure to transfer all notch markings — they\'ll guide you when joining pieces later.',
    measurement: '1.5 cm seam allowance',
    highlight: 'back',
    camera: { position: [0, 0.1, -3.2], target: [0, -0.1, 0] },
  },
  {
    id: 3,
    title: 'Pin the shoulder seams',
    description: 'Place front and back panels right sides together. Match the shoulder notches carefully and pin every 5 cm along the shoulder line.',
    measurement: '5 cm between pins',
    highlight: 'shoulder',
    camera: { position: [0, 1.8, 2.2], target: [0, 0.5, 0] },
  },
  {
    id: 4,
    title: 'Sew the shoulder seams',
    description: 'Sew along each shoulder seam with a straight stitch. Start and end with a few backstitches to lock the thread. Press the seam open with your iron.',
    measurement: '1.5 cm from edge',
    stitchType: 'Straight stitch',
    highlight: 'shoulder',
    camera: { position: [0, 1.8, 2.2], target: [0, 0.5, 0] },
  },
  {
    id: 5,
    title: 'Pin the side seams',
    description: 'Open your garment flat and fold right sides together again. Match the side notches and pin from armhole down to the hem.',
    measurement: '1.5 cm seam allowance',
    highlight: 'side',
    camera: { position: [2.8, 0, 0.5], target: [0, 0, 0] },
  },
  {
    id: 6,
    title: 'Sew the side seams',
    description: 'Sew both side seams with a straight stitch. If your fabric stretches, use a narrow zigzag stitch instead. Press seams towards the back.',
    measurement: '1.5 cm from edge',
    stitchType: 'Straight stitch',
    highlight: 'side',
    camera: { position: [2.8, 0, 0.5], target: [0, 0, 0] },
  },
  {
    id: 7,
    title: 'Attach the sleeves',
    description: 'With the body inside out, slide a sleeve in through the armhole, right sides together. Match the sleeve cap notch to the shoulder seam. Pin and sew around the armhole.',
    measurement: '1.5 cm seam allowance',
    stitchType: 'Straight stitch',
    highlight: 'sleeve',
    camera: { position: [2.2, 0.6, 1.8], target: [0.3, 0.3, 0] },
  },
  {
    id: 8,
    title: 'Hem the neckline',
    description: 'Fold the neckline edge under by 0.5 cm then again by 1 cm. Pin in place. Sew close to the fold with a straight stitch, stretching slightly as you go if the fabric is jersey.',
    measurement: '0.5 cm + 1 cm fold',
    stitchType: 'Stretch stitch',
    highlight: 'collar',
    camera: { position: [0, 2.2, 1.8], target: [0, 0.6, 0] },
  },
  {
    id: 9,
    title: 'Hem the sleeve ends',
    description: 'Fold each sleeve end under by 0.5 cm then 1.5 cm. Pin and sew in place. The key is to keep even tension all the way around.',
    measurement: '0.5 cm + 1.5 cm fold',
    stitchType: 'Straight stitch',
    highlight: 'sleeve',
    camera: { position: [2.6, -0.5, 1.0], target: [0.6, -0.2, 0] },
  },
  {
    id: 10,
    title: 'Sew the bottom hem',
    description: 'Turn up the bottom edge by 0.5 cm then 2.5 cm. Press well with your iron — this makes sewing straight so much easier. Sew close to the upper fold.',
    measurement: '0.5 cm + 2.5 cm fold',
    stitchType: 'Straight stitch',
    highlight: 'hem',
    camera: { position: [0, -1.8, 2.6], target: [0, -0.6, 0] },
  },
  {
    id: 11,
    title: 'Press all seams',
    description: 'Give every seam a final press with a hot iron. This step makes a huge difference to the finished look — professional garments are pressed at every stage.',
    highlight: 'all',
    camera: { position: [0, 0.5, 4.0], target: [0, 0, 0] },
  },
  {
    id: 12,
    title: 'Your t-shirt is finished!',
    description: 'You made this from scratch. Try it on, admire your work, and celebrate — you\'re a maker now.',
    highlight: 'all',
    camera: { position: [0, 0.5, 4.0], target: [0, 0, 0] },
  },
]

export const tshirtPatternPieces: PatternPiece[] = [
  { id: 'A', label: 'A', name: 'Front Panel', width: 52, height: 68, quantity: 1 },
  { id: 'B', label: 'B', name: 'Back Panel', width: 52, height: 66, quantity: 1 },
  { id: 'C', label: 'C', name: 'Left Sleeve', width: 38, height: 24, quantity: 1 },
  { id: 'D', label: 'D', name: 'Right Sleeve', width: 38, height: 24, quantity: 1 },
]

export const tshirtFabrics: FabricOption[] = [
  {
    name: 'Jersey Cotton',
    description: 'Soft, stretchy, and forgiving for beginners. Washes beautifully.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
  },
  {
    name: 'French Terry',
    description: 'Slightly thicker than jersey, with a looped back. Cozy and durable.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
    isEco: true,
  },
  {
    name: 'Viscose Jersey',
    description: 'Drapey and silky feel. A step up in difficulty — slippery to cut.',
    difficulty: 'Medium',
    quantityMeters: 2.0,
  },
  {
    name: 'Organic Cotton Jersey',
    description: 'Better for the environment. Slightly stiffer than regular cotton jersey.',
    difficulty: 'Easy',
    quantityMeters: 1.8,
    isEco: true,
  },
]

export const standardSizes: Record<StandardSize, UserMeasurements> = {
  XS:  { bust: 80,  waist: 62, hips: 87,  height: 164, inseam: 74 },
  S:   { bust: 84,  waist: 66, hips: 91,  height: 166, inseam: 76 },
  M:   { bust: 88,  waist: 70, hips: 95,  height: 168, inseam: 78 },
  L:   { bust: 92,  waist: 76, hips: 100, height: 170, inseam: 79 },
  XL:  { bust: 96,  waist: 82, hips: 105, height: 172, inseam: 80 },
  XXL: { bust: 102, waist: 88, hips: 112, height: 174, inseam: 81 },
}

export const getGarmentById = (id: string) =>
  garments.find((g) => g.id === id) ?? garments[0]

export const getCreatorById = (id: string) =>
  creators.find((c) => c.id === id) ?? creators[0]

export const getPatternsByCreator = (creatorId: string) =>
  creatorPatterns.filter((p) => p.creatorId === creatorId)

// ── 2D Garment Guides ────────────────────────────────────────────────────────

export const garmentGuides: GarmentGuide[] = [
  {
    garmentId: 'aline-skirt',
    pieces: [
      {
        id: 'front-panel',
        label: 'A',
        shape: 'trapezoid',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.waist / 4 + 1),
          bottomWidth: Math.round(m.hips / 4 + 4),
          height: 58,
        }),
        grainLine: 'vertical',
        seamAllowance: 1.5,
      },
      {
        id: 'back-panel',
        label: 'B',
        shape: 'trapezoid',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.waist / 4 + 1),
          bottomWidth: Math.round(m.hips / 4 + 4),
          height: 58,
        }),
        grainLine: 'vertical',
        seamAllowance: 1.5,
      },
      {
        id: 'waistband',
        label: 'C',
        shape: 'rectangle',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.waist + 3),
          bottomWidth: Math.round(m.waist + 3),
          height: 7,
        }),
        grainLine: 'horizontal',
        seamAllowance: 1.5,
      },
    ],
    steps: [
      {
        id: 1,
        group: 'Prepare',
        action: 'prepare',
        title: 'Wash and press your fabric',
        instruction: 'Wash your fabric before cutting — it will shrink slightly. Once dry, press it flat with a hot iron. This prevents your finished skirt from shrinking the first time you wash it.',
        tool: 'iron',
        tip: 'Set your iron to the heat appropriate for your fabric type. Cotton: hot. Linen: hot. Viscose: medium.',
      },
      {
        id: 2,
        group: 'Prepare',
        action: 'prepare',
        title: 'Fold your fabric',
        instruction: 'Fold your fabric in half lengthwise with the right sides facing inward. The fold runs along the grain line. This lets you cut front and back panels at the same time.',
        tip: 'Line up the selvedge edges (the finished edges of the fabric) perfectly before you start cutting.',
      },
      {
        id: 3,
        group: 'Cut the front',
        action: 'mark',
        title: 'Mark the front panel',
        instruction: 'Using tailor\'s chalk and a ruler, mark the front panel shape on your fabric. The top width goes at the fold side.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'measure-arrow', edge: 'top', label: 'top width' },
        tool: 'chalk',
        measurement: 'See dimensions on shape',
      },
      {
        id: 4,
        group: 'Cut the front',
        action: 'cut',
        title: 'Cut the front panel',
        instruction: 'Cut along your chalk lines with sharp fabric scissors. Use long, smooth strokes — don\'t use small snips. Cut through both layers of fabric at once.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom', label: '↕ cut here' },
        tool: 'scissors',
        measurement: '1.5 cm seam allowance included',
        tip: 'Keep your scissors flat on the table and move the scissors — not the fabric.',
      },
      {
        id: 5,
        group: 'Cut the back',
        action: 'mark',
        title: 'Mark the back panel',
        instruction: 'Repeat the marking on a fresh section of fabric for the back panel. The back and front are the same shape for this skirt.',
        pieceId: 'back-panel',
        fabricSide: 'wrong',
        annotation: { type: 'measure-arrow', edge: 'top', label: 'top width' },
        tool: 'chalk',
        measurement: 'Same dimensions as front panel',
      },
      {
        id: 6,
        group: 'Cut the back',
        action: 'cut',
        title: 'Cut the back panel',
        instruction: 'Cut both layers — you\'ll end up with two identical back pieces which will be joined at the centre back seam (where the zip goes).',
        pieceId: 'back-panel',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom' },
        tool: 'scissors',
        tip: 'Label the wrong side of each piece with a small chalk mark so you don\'t mix them up later.',
      },
      {
        id: 7,
        group: 'Waistband & marks',
        action: 'cut',
        title: 'Cut the waistband',
        instruction: 'Cut one waistband rectangle. The length runs along the grain line (horizontal). This piece will fold in half to form the finished waistband.',
        pieceId: 'waistband',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom' },
        tool: 'scissors',
        measurement: 'Height: 7 cm (will fold to 3 cm finished)',
      },
      {
        id: 8,
        group: 'Waistband & marks',
        action: 'mark',
        title: 'Mark seam allowances',
        instruction: 'On each piece, mark a line 1.5 cm in from the left and right edges. This is your sewing line — you sew along this, not the cut edge.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'sew-line', edge: 'left', amount: 1.5, label: '1.5 cm' },
        tool: 'chalk',
        measurement: '1.5 cm seam allowance',
        tip: 'Many sewing machines have a 1.5 cm guide marked on the needle plate — use it as a guide instead of marking every piece.',
      },
      {
        id: 9,
        group: 'Left side seam',
        action: 'pin',
        title: 'Pin the left side seam',
        instruction: 'Place the front panel and one back panel right sides together. The fabric\'s "nice" side faces inward. Pin along the left edge every 5 cm.',
        pieceId: 'front-panel',
        fabricSide: 'right',
        annotation: { type: 'pin-row', edge: 'left' },
        tool: 'pins',
        tip: 'Place pins perpendicular to the edge (pointing into the fabric) so you can sew over them slowly without breaking your needle.',
      },
      {
        id: 10,
        group: 'Left side seam',
        action: 'sew',
        title: 'Sew the left side seam',
        instruction: 'Sew along the left edge, 1.5 cm from the cut edge. Start and end with 3–4 backstitches to lock the thread. Remove pins as you reach them.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'sew-line', edge: 'left', amount: 1.5 },
        tool: 'needle',
        measurement: '1.5 cm from edge',
        tip: 'Sew slowly and steadily. Speed is not your friend when you\'re learning.',
      },
      {
        id: 11,
        group: 'Left side seam',
        action: 'press',
        title: 'Press the left seam open',
        instruction: 'Open the two pieces flat and press the seam allowance open with your iron. This makes the seam lie flat and look professional.',
        pieceId: 'front-panel',
        tool: 'iron',
        tip: 'Press from the right side of the fabric with a pressing cloth to avoid shine marks.',
      },
      {
        id: 12,
        group: 'Right side seam',
        action: 'pin',
        title: 'Pin the right side seam',
        instruction: 'Pin the front panel to the remaining back panel along the right edge, right sides together.',
        pieceId: 'front-panel',
        fabricSide: 'right',
        annotation: { type: 'pin-row', edge: 'right' },
        tool: 'pins',
      },
      {
        id: 13,
        group: 'Right side seam',
        action: 'sew',
        title: 'Sew the right side seam',
        instruction: 'Sew the right side seam, leaving the top 18 cm open — this is where the zip will go. Mark the 18 cm point with a pin before you start.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'sew-line', edge: 'right', amount: 1.5 },
        tool: 'needle',
        measurement: 'Leave 18 cm open at top',
        tip: 'Backstitch firmly at the point where you stop sewing — this is under tension when you put the zip in.',
      },
      {
        id: 14,
        group: 'Right side seam',
        action: 'press',
        title: 'Press the right seam',
        instruction: 'Press the right seam open, including the unsewn section at the top. Fold and press the seam allowance back on the open section — this preps the zip opening.',
        pieceId: 'front-panel',
        tool: 'iron',
      },
      {
        id: 15,
        group: 'Attach the waistband',
        action: 'fold',
        title: 'Fold the waistband in half',
        instruction: 'Fold the waistband piece in half lengthwise, wrong sides together. Press the fold firmly. The folded piece is now 3.5 cm tall.',
        pieceId: 'waistband',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'bottom', amount: 3.5, label: 'fold here' },
        tool: 'iron',
      },
      {
        id: 16,
        group: 'Attach the waistband',
        action: 'pin',
        title: 'Pin waistband to skirt top',
        instruction: 'Open the waistband back out. Place it right sides together with the skirt top edge, matching the raw edges. Pin along the top.',
        pieceId: 'waistband',
        fabricSide: 'right',
        annotation: { type: 'pin-row', edge: 'bottom' },
        tool: 'pins',
        measurement: 'Align raw edges exactly',
      },
      {
        id: 17,
        group: 'Attach the waistband',
        action: 'sew',
        title: 'Sew the waistband on',
        instruction: 'Sew the waistband to the skirt top, 1.5 cm from the edge. Sew all the way around.',
        pieceId: 'waistband',
        annotation: { type: 'sew-line', edge: 'bottom', amount: 1.5 },
        tool: 'needle',
        measurement: '1.5 cm seam allowance',
      },
      {
        id: 18,
        group: 'Close the waistband',
        action: 'fold',
        title: 'Fold waistband to inside',
        instruction: 'Fold the waistband over to the inside of the skirt along the original pressed fold line. The folded edge should just cover the seam line.',
        pieceId: 'waistband',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'top', label: 'fold to inside' },
      },
      {
        id: 19,
        group: 'Close the waistband',
        action: 'pin',
        title: 'Pin waistband edge',
        instruction: 'Pin the folded waistband edge to the inside of the skirt, just below the seam line.',
        pieceId: 'waistband',
        fabricSide: 'wrong',
        annotation: { type: 'pin-row', edge: 'top' },
        tool: 'pins',
      },
      {
        id: 20,
        group: 'Close the waistband',
        action: 'sew',
        title: 'Topstitch the waistband',
        instruction: 'From the right side, topstitch 2 mm from the upper folded edge of the waistband all the way around. This secures the inside edge.',
        pieceId: 'waistband',
        fabricSide: 'right',
        annotation: { type: 'sew-line', edge: 'top', amount: 0.2, label: '2 mm topstitch' },
        tool: 'needle',
        measurement: '2 mm from folded edge',
      },
      {
        id: 21,
        group: 'Fold the hem',
        action: 'fold',
        title: 'Fold first hem',
        instruction: 'Turn the skirt wrong side out. Fold the bottom edge up by 1 cm all the way around. Press firmly.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'bottom', amount: 1, label: '1 cm fold' },
        tool: 'iron',
        measurement: '1 cm fold',
      },
      {
        id: 22,
        group: 'Fold the hem',
        action: 'fold',
        title: 'Fold second hem',
        instruction: 'Fold the bottom up again by 2.5 cm. Press well. This double fold gives a clean, durable hem with no raw edges.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'bottom', amount: 2.5, label: '2.5 cm fold' },
        tool: 'iron',
        measurement: '2.5 cm second fold',
        tip: 'A hem gauge ruler makes this so much easier — you can measure and fold at the same time.',
      },
      {
        id: 23,
        group: 'Sew the hem',
        action: 'pin',
        title: 'Pin the hem',
        instruction: 'Pin the folded hem in place around the full circumference of the skirt.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'pin-row', edge: 'bottom' },
        tool: 'pins',
      },
      {
        id: 24,
        group: 'Sew the hem',
        action: 'sew',
        title: 'Sew the hem',
        instruction: 'Sew close to the upper fold of the hem, all the way around. Keep a steady seam allowance of about 2 mm from the fold.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'sew-line', edge: 'bottom', amount: 0.2 },
        tool: 'needle',
        measurement: '2 mm from folded edge',
        tip: 'Go slowly on the hem — uneven hem stitching is very visible on the finished garment.',
      },
      {
        id: 25,
        group: 'Finish',
        action: 'press',
        title: 'Final press',
        instruction: 'Give the entire skirt a thorough press — seams, waistband, and hem. This is what separates a homemade-looking garment from a professional one.',
        tool: 'iron',
        tip: 'Press on the wrong side to avoid shine. Use a damp cloth or steam for stubborn wrinkles.',
      },
    ],
  },
  {
    garmentId: 'classic-tshirt',
    pieces: [
      {
        id: 'front-panel',
        label: 'A',
        shape: 'trapezoid',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.bust / 4 + 2),
          bottomWidth: Math.round(m.hips / 4 + 3),
          height: Math.round(m.height * 0.38),
        }),
        grainLine: 'vertical',
        seamAllowance: 1.5,
      },
      {
        id: 'back-panel',
        label: 'B',
        shape: 'trapezoid',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.bust / 4 + 2),
          bottomWidth: Math.round(m.hips / 4 + 3),
          height: Math.round(m.height * 0.38),
        }),
        grainLine: 'vertical',
        seamAllowance: 1.5,
      },
      {
        id: 'sleeve',
        label: 'C',
        shape: 'trapezoid',
        dims: (m: UserMeasurements) => ({
          topWidth: Math.round(m.bust / 4 + 1),
          bottomWidth: Math.round(m.bust / 6),
          height: Math.round(m.height * 0.14),
        }),
        grainLine: 'vertical',
        seamAllowance: 1.5,
      },
    ],
    steps: [
      {
        id: 1,
        group: 'Prepare',
        action: 'prepare',
        title: 'Wash and press your fabric',
        instruction: 'Wash and dry your fabric before cutting to pre-shrink it. Press flat with an iron.',
        tool: 'iron',
      },
      {
        id: 2,
        group: 'Cut',
        action: 'cut',
        title: 'Cut the front panel',
        instruction: 'Fold fabric in half, right sides together. Mark and cut the front panel, leaving 1.5 cm seam allowance on all sides.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom' },
        tool: 'scissors',
        measurement: '1.5 cm seam allowance',
      },
      {
        id: 3,
        group: 'Cut',
        action: 'cut',
        title: 'Cut the back panel',
        instruction: 'Cut the back panel the same way as the front.',
        pieceId: 'back-panel',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom' },
        tool: 'scissors',
      },
      {
        id: 4,
        group: 'Cut',
        action: 'cut',
        title: 'Cut the sleeves',
        instruction: 'Cut two sleeve pieces — flip the pattern to cut a left and right sleeve.',
        pieceId: 'sleeve',
        fabricSide: 'wrong',
        annotation: { type: 'cut-line', edge: 'bottom' },
        tool: 'scissors',
        tip: 'Mark "Left" and "Right" on the wrong side with chalk.',
      },
      {
        id: 5,
        group: 'Shoulders',
        action: 'pin',
        title: 'Pin shoulder seams',
        instruction: 'Place front and back right sides together. Pin along both shoulder edges.',
        pieceId: 'front-panel',
        fabricSide: 'right',
        annotation: { type: 'pin-row', edge: 'top' },
        tool: 'pins',
      },
      {
        id: 6,
        group: 'Shoulders',
        action: 'sew',
        title: 'Sew shoulder seams',
        instruction: 'Sew both shoulder seams, 1.5 cm from the edge. Backstitch at start and end.',
        pieceId: 'front-panel',
        annotation: { type: 'sew-line', edge: 'top', amount: 1.5 },
        tool: 'needle',
        measurement: '1.5 cm from edge',
      },
      {
        id: 7,
        group: 'Shoulders',
        action: 'press',
        title: 'Press shoulder seams open',
        instruction: 'Press both shoulder seams open flat.',
        pieceId: 'front-panel',
        tool: 'iron',
      },
      {
        id: 8,
        group: 'Neckline',
        action: 'fold',
        title: 'Hem the neckline',
        instruction: 'Fold the neckline edge down 0.5 cm, then again 1 cm. Press and pin.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'top', amount: 1, label: '0.5 + 1 cm fold' },
        tool: 'iron',
        measurement: '0.5 cm + 1 cm fold',
      },
      {
        id: 9,
        group: 'Neckline',
        action: 'sew',
        title: 'Sew the neckline hem',
        instruction: 'Sew close to the inner fold around the full neckline.',
        pieceId: 'front-panel',
        annotation: { type: 'sew-line', edge: 'top', amount: 0.2 },
        tool: 'needle',
      },
      {
        id: 10,
        group: 'Sleeves',
        action: 'attach',
        title: 'Attach sleeves',
        instruction: 'With the body inside out, slide a sleeve through the armhole, right sides together. Match the sleeve cap notch to the shoulder seam. Pin and sew around the armhole.',
        pieceId: 'sleeve',
        annotation: { type: 'sew-line', edge: 'top', amount: 1.5 },
        tool: 'needle',
        measurement: '1.5 cm seam allowance',
      },
      {
        id: 11,
        group: 'Side seams',
        action: 'pin',
        title: 'Pin side seams',
        instruction: 'Fold right sides together again. Pin from armhole down through sleeve and body to the hem on both sides.',
        pieceId: 'front-panel',
        fabricSide: 'right',
        annotation: { type: 'pin-row', edge: 'left' },
        tool: 'pins',
      },
      {
        id: 12,
        group: 'Side seams',
        action: 'sew',
        title: 'Sew side seams',
        instruction: 'Sew both side seams in one continuous line from sleeve cuff to shirt hem.',
        pieceId: 'front-panel',
        annotation: { type: 'sew-line', edge: 'left', amount: 1.5 },
        tool: 'needle',
        measurement: '1.5 cm from edge',
      },
      {
        id: 13,
        group: 'Sleeve hems',
        action: 'fold',
        title: 'Hem the sleeves',
        instruction: 'Fold each sleeve cuff up 0.5 cm then 1.5 cm. Press and pin.',
        pieceId: 'sleeve',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'bottom', amount: 1.5, label: '0.5 + 1.5 cm' },
        tool: 'iron',
        measurement: '0.5 cm + 1.5 cm fold',
      },
      {
        id: 14,
        group: 'Sleeve hems',
        action: 'sew',
        title: 'Sew sleeve hems',
        instruction: 'Sew close to the inner fold on both sleeve cuffs.',
        pieceId: 'sleeve',
        annotation: { type: 'sew-line', edge: 'bottom', amount: 0.2 },
        tool: 'needle',
      },
      {
        id: 15,
        group: 'Bottom hem',
        action: 'fold',
        title: 'Fold bottom hem',
        instruction: 'Fold the shirt hem up 0.5 cm then 2.5 cm. Press firmly.',
        pieceId: 'front-panel',
        fabricSide: 'wrong',
        annotation: { type: 'fold-line', edge: 'bottom', amount: 2.5, label: '0.5 + 2.5 cm' },
        tool: 'iron',
        measurement: '0.5 cm + 2.5 cm fold',
      },
      {
        id: 16,
        group: 'Bottom hem',
        action: 'sew',
        title: 'Sew the bottom hem',
        instruction: 'Sew close to the inner fold all the way around the hem.',
        pieceId: 'front-panel',
        annotation: { type: 'sew-line', edge: 'bottom', amount: 0.2 },
        tool: 'needle',
      },
      {
        id: 17,
        group: 'Finish',
        action: 'press',
        title: 'Final press',
        instruction: 'Press the entire t-shirt — seams, hems, and all. You\'re done.',
        tool: 'iron',
        tip: 'Turn inside out to press seams without shine.',
      },
    ],
  },
]

export const getGarmentGuide = (garmentId: string) =>
  garmentGuides.find((g) => g.garmentId === garmentId) ?? null
